### ISSUE TITLE
One-to-many index support

### ISSUE THREAD

**Issue by antonkatz** [hypermodules/level-auto-index#33]
Does `level-auto-index` support aggregating multiple keys/object under a single index lookup? 

For example, a chat app:
A message belongs to a room
I want an index by which I can look up all the messages in the same room

I have not been able to figure out how to do that with `level-auto-index`

**Comment by bcomnes** [comment]
Like have a index key pointing to an ever increasing array of msg pointers?

No. The way you would do this is create an index key with the room prefix ! Date time ! post id for each message in the index. Then you create a read stream of the room index and that should get you an optimized scan of all those messages. 

If a msg can be sent to multiple rooms, you could recycle the tag example in the readme. 

You might even consider keeping your primary database keys sorted like this and you wouldn’t evens need an index most likely.

**Comment by bcomnes** [comment]
You could use the lower level modules to do the proposed ideas however taking advantage of the built in level key sorting is an important concern when using level.

**Comment by bcomnes** [comment]
Apologies if I didn’t quite understand the request in advance.

**Comment by antonkatz** [comment]
@bcomnes you're right. Your solution with the prefixes is the way it needs to be done. 
It's very obvious to me now after thinking about it properly.

**Comment by antonkatz** [comment]
Thank you for making me a better programmer :)

**Comment by bcomnes** [comment]
Great! Glad to help out.  Level is simple, but not intuitive without knowing a few of these tricks first.
